const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const toast=m=>{const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2800)};addEventListener("load",()=>setTimeout(()=>$("#intro")?.classList.add("done"),1750));
const themes=["","velvet","champagne"];let themeIndex=Number(localStorage.getItem("piaTheme")||0);if(!Number.isFinite(themeIndex))themeIndex=0;function setTheme(n,silent=false){themeIndex=(n+themes.length)%themes.length;document.documentElement.dataset.theme=themes[themeIndex];localStorage.setItem("piaTheme",themeIndex);if(!silent)toast(["Rose mood ✦","Velvet mood ✦","Champagne mood ✦"][themeIndex])}setTheme(themeIndex,true);$("#theme").onclick=()=>setTheme(themeIndex+1);
const progress=$("#scrollProgress"),nav=$("#nav");addEventListener("scroll",()=>{const h=document.documentElement;progress.style.width=Math.min(100,scrollY/(h.scrollHeight-innerHeight)*100)+"%";nav.classList.toggle("scrolled",scrollY>20)},{passive:true});const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("on")}),{threshold:.1});$$(".reveal").forEach(x=>observer.observe(x));
const compliments=["You're beautiful, but the confidence behind it is what makes you magnetic.","That little bit of sass? Keep it. It suits you.","You don't need to compete with anyone. Your vibe is already your own.","Your smile can completely change the mood of a room.","You are absolutely allowed to look in the mirror and think: yeah, I look good.","Soft, bold, glamorous, playful — every version of you deserves love.","The outfit gets noticed. Your personality is what makes it unforgettable.","You have that rare mix of sweetness and attitude that makes people remember you."];function openCompliment(text){$("#modalText").textContent=text||compliments[Math.floor(Math.random()*compliments.length)];$("#modal").classList.add("open");$("#modal").setAttribute("aria-hidden","false")}$("#compliment").onclick=()=>openCompliment();$("#love").onclick=()=>openCompliment("You deserve to feel adored, appreciated, beautiful and completely yourself — not just today, but on ordinary days too.");$("#close").onclick=()=>{$("#modal").classList.remove("open");$("#modal").setAttribute("aria-hidden","true")};$("#modal").onclick=e=>{if(e.target===$("#modal"))$("#close").click()};
$$(".note-grid button").forEach(b=>b.onclick=()=>{toast(b.dataset.note);b.animate([{transform:"scale(1)"},{transform:"scale(.96)"},{transform:"scale(1)"}],{duration:260})});$$(".photo-card").forEach(b=>b.onclick=()=>toast(b.dataset.slot+" — ready for her photo ✦"));const quotes=["She can be soft without being small, confident without apologising, and gorgeous without trying to prove it.","Pretty is the first impression. Her personality is the plot twist.","She doesn't need a spotlight. Somehow, she creates one.","A little sweetness, a little attitude, and a whole lot of her.","The best look is still the one where she feels completely herself.","She is allowed to take up space, look amazing and enjoy every second of it."];let qi=0;$("#another").onclick=()=>{qi=(qi+1)%quotes.length;const q=$("#quote");q.animate([{opacity:0,transform:"translateY(10px)"},{opacity:1,transform:"none"}],{duration:350});setTimeout(()=>q.textContent=quotes[qi],80)};
const moods={
soft:["SOFT SIDE","Pretty can be gentle.","The kind of presence that makes ordinary moments feel warmer."],
sassy:["SASSY SIDE","Sweet face. Sharp sparkle.","A little attitude is part of the charm — and she wears it well."],
glam:["GLAM SIDE","Let the room notice.","Elegant, magnetic and completely comfortable taking the spotlight."],
mystery:["MYSTERY SIDE","Leave a little unsaid.","Some energy is better felt than explained."],
playful:["PLAYFUL SIDE","Pretty with a plot twist.","The laugh, the chaos, the tiny mischief — all part of the magic."]
};
const experienceStage=$("#experienceStage"),label=$("#moodLabel"),title=$("#moodTitle"),copy=$("#moodText");
function setMood(name){const m=moods[name]||moods.soft;experienceStage.dataset.mood=name;label.textContent=m[0];title.textContent=m[1];copy.textContent=m[2];$$(".mood").forEach(b=>b.classList.toggle("active",b.dataset.mood===name))}
$$(".mood").forEach(b=>b.onclick=()=>setMood(b.dataset.mood));
$("#moodSurprise").onclick=()=>{const keys=Object.keys(moods);setMood(keys[Math.floor(Math.random()*keys.length)]);toast("A different side of Pia ✦")};
$(".memory-card").forEach((b,i)=>b.onclick=()=>toast(["A moment worth keeping ✦","That laugh deserves its own frame ♡","The little things are often the biggest things.","Leave room for the next beautiful memory ✦"][i]));
$("#secretReveal").onclick=()=>{const messages=["Some girls have a look. Pia has an atmosphere.","A little mystery makes every story more interesting ✦","She deserves compliments on ordinary days too.","Keep the confidence. Keep the softness. Keep the sparkle.","This corner of the internet is officially a Pia appreciation zone. ♡"];$("#secretMessage").textContent=messages[Math.floor(Math.random()*messages.length)];$("#secretReveal").animate([{transform:"scale(1) rotate(0)"},{transform:"scale(1.2) rotate(18deg)"},{transform:"scale(1) rotate(0)"}],{duration:500});toast("Secret unlocked ✦")};
const starWords={confidence:"Confidence — the freedom to take up space as yourself.",kindness:"Kindness — the little warmth people remember.",style:"Style — the way personal taste becomes a signature.",humour:"Humour — making ordinary moments lighter.",attitude:"Attitude — a little spark that makes the energy unmistakably hers."};
$(".constellation-board button").forEach(b=>b.onclick=()=>{$("#starMessage").textContent=starWords[b.dataset.star];b.animate([{transform:"scale(1)"},{transform:"scale(1.7)"},{transform:"scale(1)"}],{duration:420})});
let dragging=false,lastX=0,lastY=0,rotX=0,rotY=0;const stage=$("#moonStage"),moon=$("#moonStage .big-moon"),paint=()=>{moon.style.transform="rotateX("+rotX+"deg) rotateY("+rotY+"deg)"};stage.addEventListener("pointerdown",e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;stage.setPointerCapture?.(e.pointerId)});stage.addEventListener("pointermove",e=>{if(!dragging)return;rotY=Math.max(-28,Math.min(28,rotY+(e.clientX-lastX)*.28));rotX=Math.max(-18,Math.min(18,rotX-(e.clientY-lastY)*.18));lastX=e.clientX;lastY=e.clientY;paint()});stage.addEventListener("pointerup",()=>dragging=false);stage.addEventListener("pointercancel",()=>dragging=false);$("#moonlight").onclick=()=>{document.body.classList.toggle("moonlight");toast(document.body.classList.contains("moonlight")?"Moonlight mode on ☾":"Moonlight mode off")};$("#top").onclick=()=>scrollTo({top:0,behavior:"smooth"});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&$("#modal").classList.contains("open"))$("#close").click();if(e.key.toLowerCase()==="t")setTheme(themeIndex+1)});