const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const toast=m=>{const t=$("#toast");if(!t)return;t.textContent=m;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2600)};
window.addEventListener("load",()=>setTimeout(()=>$("#loader")?.classList.add("done"),1500));
const themes=["light-pink","light-cream","bright","velvet","champagne"];let themeIndex=Number(localStorage.getItem("piaTheme")||0);if(!Number.isFinite(themeIndex)||themeIndex>=themes.length)themeIndex=0;
function setTheme(n){themeIndex=(n+themes.length)%themes.length;document.documentElement.dataset.theme=themes[themeIndex];document.body.classList.toggle("bright-mode",["light-pink","light-cream","bright"].includes(themes[themeIndex]));localStorage.setItem("piaTheme",themeIndex);toast(["Pink light ✦","Cream light ✦","Bright love ✦","Velvet mood ✦","Champagne mood ✦"][themeIndex])}
$("#theme")?.addEventListener("click",()=>setTheme(themeIndex+1));document.documentElement.dataset.theme=themes[themeIndex];document.body.classList.toggle("bright-mode",["light-pink","light-cream","bright"].includes(themes[themeIndex]));
const nav=$("#nav");window.addEventListener("scroll",()=>nav?.classList.toggle("scrolled",scrollY>20),{passive:true});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.08});$$(".reveal").forEach(x=>io.observe(x));
const compliments=["Your confidence is part of what makes you magnetic.","That little bit of sass? Keep it. It suits you.","You never need to compete with anyone. Your vibe is your own.","You are allowed to look in the mirror and think: yeah, I look good.","Soft, bold, glamorous or playful — every version of you deserves love."];
function modal(msg){$("#modalText").textContent=msg;$("#modal").classList.add("open")}$("#compliment")?.addEventListener("click",()=>modal(compliments[Math.floor(Math.random()*compliments.length)]));$("#love")?.addEventListener("click",()=>modal("You deserve to feel adored, appreciated, beautiful and completely yourself — even on ordinary days."));$("#close")?.addEventListener("click",()=>$("#modal").classList.remove("open"));$("#modal")?.addEventListener("click",e=>{if(e.target.id==="modal")$("#modal").classList.remove("open")});
const moods={soft:["SOFT SIDE","Pretty can be gentle.","The kind of presence that makes ordinary moments feel warmer."],sassy:["SASSY SIDE","Sweet face. Sharp sparkle.","A little attitude is part of the charm — and she wears it well."],glam:["GLAM SIDE","Let the room notice.","Elegant, magnetic and completely comfortable taking the spotlight."],mystery:["MYSTERY SIDE","Leave a little unsaid.","Some energy is better felt than explained."],playful:["PLAYFUL SIDE","Pretty with a plot twist.","The laugh, the chaos, the tiny mischief — all part of the magic."]};
const stage=$("#experienceStage");function mood(name){const m=moods[name]||moods.soft;stage.dataset.mood=name;$("#moodLabel").textContent=m[0];$("#moodTitle").textContent=m[1];$("#moodText").textContent=m[2];$$(".mood").forEach(b=>b.classList.toggle("active",b.dataset.mood===name))}
$$(".mood").forEach(b=>b.addEventListener("click",()=>mood(b.dataset.mood)));$("#surprise")?.addEventListener("click",()=>{const k=Object.keys(moods);mood(k[Math.floor(Math.random()*k.length)]);toast("A different side of Pia ✦")});
$$(".memory,.note").forEach(b=>b.addEventListener("click",()=>toast(b.dataset.msg||"A little reminder for Pia ✦")));
$$(".photo").forEach(b=>b.addEventListener("click",()=>toast("This is a clean photo slot — no random image added ✦")));
const secrets=["Some girls have a look. Pia has an atmosphere.","Keep the confidence. Keep the softness. Keep the sparkle.","This corner of the internet is officially a Pia appreciation zone. ♡","A little mystery makes every story more interesting ✦"];$("#secret")?.addEventListener("click",()=>{$("#secretText").textContent=secrets[Math.floor(Math.random()*secrets.length)];toast("Secret unlocked ✦")});
$$(".sky button").forEach(b=>b.addEventListener("click",()=>{$("#starText").textContent=b.dataset.star}));
let down=false,lx=0,ly=0,rx=0,ry=0;const ms=$("#moonStage"),moon=$("#moonStage .big-moon");const paint=()=>moon.style.transform="rotateX("+rx+"deg) rotateY("+ry+"deg)";ms?.addEventListener("pointerdown",e=>{down=true;lx=e.clientX;ly=e.clientY;ms.setPointerCapture?.(e.pointerId)});ms?.addEventListener("pointermove",e=>{if(!down)return;ry=Math.max(-30,Math.min(30,ry+(e.clientX-lx)*.25));rx=Math.max(-20,Math.min(20,rx-(e.clientY-ly)*.18));lx=e.clientX;ly=e.clientY;paint()});["pointerup","pointercancel"].forEach(x=>ms?.addEventListener(x,()=>down=false));$("#moonlight")?.addEventListener("click",()=>{document.body.classList.toggle("moonlight-mode");toast(document.body.classList.contains("moonlight-mode")?"Moonlight on ☾":"Moonlight off")});
$("#top")?.addEventListener("click",()=>scrollTo({top:0,behavior:"smooth"}));document.addEventListener("keydown",e=>{if(e.key==="Escape")$("#modal")?.classList.remove("open");if(e.key.toLowerCase()==="t")setTheme(themeIndex+1)});
// cinematic interaction layer
(()=>{
 const progress=document.createElement("div");progress.className="scroll-progress";document.body.appendChild(progress);
 const glow=document.createElement("div");glow.className="cursor-glow";document.body.appendChild(glow);
 addEventListener("scroll",()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max>0?scrollY/max*100:0)+"%";},{passive:true});
 addEventListener("pointermove",e=>{if(innerWidth<700)return;glow.style.opacity=".8";glow.style.left=e.clientX+"px";glow.style.top=e.clientY+"px";},{passive:true});
 addEventListener("pointerleave",()=>glow.style.opacity="0");
 const tilt=el=>{el.addEventListener("pointermove",e=>{if(innerWidth<700)return;const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform="perspective(700px) rotateX("+(-y*5)+"deg) rotateY("+(x*5)+"deg) translateY(-5px)";},{passive:true});el.addEventListener("pointerleave",()=>el.style.transform="");};
 $$(".energy-grid article,.memory,.photo,.note,.attitude-grid article,.ribbon article").forEach(tilt);
 const burst=(x,y)=>{for(let i=0;i<12;i++){const s=document.createElement("span");s.className="heart-particle";s.textContent=i%3===0?"♡":"✦";s.style.left=x+"px";s.style.top=y+"px";s.style.setProperty("--dx",(Math.random()*150-75)+"px");s.style.setProperty("--rot",(Math.random()*80-40)+"deg");document.body.appendChild(s);setTimeout(()=>s.remove(),1800)}};
 let count=Number(localStorage.getItem("piaAdmireCount")||0);const counter=document.createElement("div");counter.className="love-counter";counter.innerHTML="<span>♡</span><b>"+count+"</b><small>little moments</small>";document.body.appendChild(counter);
 document.addEventListener("click",e=>{const b=e.target.closest("#compliment,#love,.photo,.note,.memory");if(!b)return;if(b.matches("#compliment,#love")){count++;localStorage.setItem("piaAdmireCount",count);counter.querySelector("b").textContent=count;burst(e.clientX,e.clientY)}});
 const moon=document.querySelector(".big-moon");if(moon){let t=0;setInterval(()=>{if(!document.hidden){t+=.012;moon.style.filter="drop-shadow(0 0 "+(25+Math.sin(t)*10)+"px rgba(244,210,141,.18))"}},40)}
})();

/* fourth-dimension interaction */
(()=>{const core=document.querySelector("#dimensionCore"),btn=document.querySelector("#dimensionBtn"),msg=document.querySelector("#dimensionMessage");if(!core||!btn||!msg)return;const lines=["She is the kind of beautiful you notice twice.","If admiration had a favourite person, it would probably be her.","Pretty is the first impression. Her energy is the reason you stay.","Some smiles deserve their own little universe.","She does not need a spotlight — she somehow creates one.","For Pia: more softness, more laughter, more moments worth remembering."];let n=0;btn.addEventListener("click",()=>{core.classList.add("active");n=(n+1)%lines.length;msg.textContent=lines[n];toast("A little more love ✦");setTimeout(()=>core.classList.remove("active"),1800)});core.addEventListener("pointermove",e=>{if(innerWidth<700)return;const r=core.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;core.style.transform="rotateX("+(-y*10)+"deg) rotateY("+(x*14)+"deg) scale(1.02)"});core.addEventListener("pointerleave",()=>core.style.transform="")})();


/* Pia intro interaction — isolated */
(()=>{const b=document.querySelector("#introLove");if(!b)return;const notes=["If I could bottle one feeling, it would be the way you make an ordinary day feel special.","You do not have to try so hard to be unforgettable. Somehow, you already are.","A little reminder: your smile, your softness and your spark are all worth being adored.","For Pia: may you always see yourself with the same warmth that the people who love you see in you."];let i=0;b.addEventListener("click",()=>{i=(i+1)%notes.length;modal(notes[i]);toast("For Pia, with love ♡")})})();

/* Cinematic intro + reliable moonlight controls */
(()=>{const intro=document.querySelector("#cinematicIntro"),enter=document.querySelector("#cinematicEnter");if(intro){const close=()=>{intro.classList.add("hide");setTimeout(()=>intro.remove(),1300)};enter?.addEventListener("click",e=>{e.stopPropagation();close()});intro.addEventListener("click",e=>{if(e.target===intro)close()});setTimeout(close,6500)}})();
(()=>{const b=document.querySelector("#moonlight");if(!b)return;const sync=()=>{const on=document.body.classList.contains("moonlight-mode");b.textContent=on?"Turn off moonlight ☾":"Turn on moonlight ☾";b.setAttribute("aria-pressed",String(on))};b.addEventListener("click",()=>{document.body.classList.toggle("moonlight-mode");sync();toast(document.body.classList.contains("moonlight-mode")?"Moonlight is glowing ✦":"Moonlight off");});sync()})();

/* Bright theme + love ambience — additive only */
(()=>{const b=document.querySelector("#theme");if(!b)return;const old=window.setTheme;window.setTheme=old;})();
(()=>{const root=document.documentElement,btn=document.querySelector("#theme");const key="piaBrightMode";if(localStorage.getItem(key)==="1")document.body.classList.add("bright-mode");const sync=()=>{if(!btn)return;const on=document.body.classList.contains("bright-mode");btn.setAttribute("aria-label",on?"Switch to dark theme":"Switch to bright theme");btn.textContent=on?"☼":"◐"};btn?.addEventListener("dblclick",()=>{document.body.classList.toggle("bright-mode");localStorage.setItem(key,document.body.classList.contains("bright-mode")?"1":"0");sync();toast(document.body.classList.contains("bright-mode")?"Bright love mode ✦":"Dark mode restored");});sync();})();
(()=>{const layer=document.createElement("div");layer.className="love-spark-layer";document.body.appendChild(layer);const burst=(count=9)=>{for(let i=0;i<count;i++){const s=document.createElement("span");s.className="love-spark"+(Math.random()>.55?" heart":"");s.textContent=Math.random()>.45?"♡":"✦";s.style.left=(15+Math.random()*70)+"%";s.style.top=(42+Math.random()*28)+"%";s.style.setProperty("--dx",(Math.random()*160-80)+"px");s.style.setProperty("--rot",(Math.random()*90-45)+"deg");s.style.animationDelay=(Math.random()*.35)+"s";layer.appendChild(s);setTimeout(()=>s.remove(),5600)}};document.querySelector("#love")?.addEventListener("click",()=>burst(16));document.querySelector("#compliment")?.addEventListener("click",()=>burst(10));document.querySelector("#introLove")?.addEventListener("click",()=>burst(12));document.querySelector("#dimensionBtn")?.addEventListener("click",()=>burst(12));})();